server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /config.json {
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
